name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip coverage
          pip install -r requirements.txt

      - name: Test package with coverage
        run: |
          coverage run -m unittest discover tests

      - name: Generate coverage report
        run: |
          coverage report -m
