name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release version
        run: |
          IMAGE_TAG=`echo $GITHUB_REF | sed 's#.*/v##'`
          echo "Setting Docker image tag to ${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          sed -i "s/<latest_tag_placeholder>/${IMAGE_TAG}/" ./deployment/docker/README.md

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./deployment/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: olivergregorius/sun2000-rest:${{ env.IMAGE_TAG }},olivergregorius/sun2000-rest:latest

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: olivergregorius/sun2000-rest
          short-description: RESTful interface for reading Huawei Sun2000 inverter metrics.
          readme-filepath: ./deployment/docker/README.md
