name: Publish

#on:
#  release:
#    types:
#      - published

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release version
        run: |
          # IMAGE_TAG=`echo $GITHUB_REF | sed 's#.*/v##'`
          IMAGE_TAG=testing
          echo "IMAGE_TAG=${IMAGE_TAG} >> $GITHUB_ENV
          echo "Setting Docker image tag to ${IMAGE_TAG}"

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deployment/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: olivergregorius/sun2000-rest:${{ env.IMAGE_TAG }}
